Add initial support for Markdown
paulkim26/til-to-html pull request #13
Opened 2023-09-20 21:09 UTC by mismathh

Resolves #9 

- Updated `parseArguments.ts` to also check if input path ends in `.md` 
- Created `parseHeadingTwo.ts` file inside `./src/parse-markdown` folder and added function to replace Heading 2 markdown syntax with appropriate `<h2>...</h2>` HTML tag
    - Within `./src/parse-markdown/index.ts`, the input text is being split into singular lines, but since the alternative Heading 2 syntax is based on two lines (alternate syntax is having a form of  `---` on the line after the desired Heading 2 line), I needed to join back the lines that matched this type of syntax, and then push it to the `parseBlock(paragraph)` function
- Updated `parseBlock.ts` to run `parseHeadingTwo` function within `parseBlock` function
- Added `.md` sample files inside ./examples folder
- Updated README to include file extensions that are supported

2023-09-20 22:04 UTC, paulkim26 requested changes
Looks good, just have some minor comments here and there.

2023-09-20 22:04 UTC, paulkim26 commented on src/parse-markdown/index.ts
> +        lineHtml += `${parsedParagraph}`;
No need for template syntax, can simply do:
```ts
lineHtml += parsedParagraph;
```

2023-09-20 22:04 UTC, paulkim26 commented on src/parse-markdown/parseHeadingTwo.ts
> +    let headingTwo = headingTwoText.split(/##/).slice(1).join("##").trim();
I prefer using `const` whenever possible if a value does not need to be mutated within its scope.

2023-09-20 22:04 UTC, paulkim26 commented on src/parse-markdown/parseHeadingTwo.ts
> +    let altHeadingTwo = headingTwoText.split(/\n/)[0].trim();
I prefer using `const` whenever possible if a value does not need to be mutated within its scope. I'd also prefer using the same variable `headingTwo` like last time since it's a good variable name and the two scopes are distinct.

2023-09-20 22:04 UTC, paulkim26 commented on src/parse-markdown/index.ts
> +  for (let i = 0; i < paragraphs.length; i++) {
Can eliminate checking for condition `i < paragraphs.length - 1` by limiting the iteration condition.

```ts
for (let i = 0; i < (paragraphs.length - 1); i++) {
  if (i < paragraphs[i + 1].match(/^( {0,3}-+\s*)$/) !== null) {
    paragraphs[i] = `${paragraphs[i]}\n${paragraphs[i + 1]}`;
    paragraphs[i + 1] = "";
  }
}
```

2023-09-20 22:04 UTC, paulkim26 commented on src/parse-markdown/index.ts
> +    if (i < paragraphs.length - 1 && paragraphs[i + 1].match(/^( {0,3}-+\s*)$/) != null) {
Strict type checking operators are preferred (`!==`)

2023-09-21 00:25 UTC, mismathh commented
I have completed making the necessary changes.

2023-09-21 00:30 UTC, paulkim26 approved these changes
Looks great! Thanks

2023-09-21 00:31 UTC, merged